version: '3.7'

services:
  http:
    build:
      context: ./crates/http
      dockerfile: Dockerfile
    ports:
      - "8181:4000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - WEB_SERVER_PORT=4000
      - NUM_WORKERS=1
      - LOG_LEVEL="info"
    networks:
      - dii

  pubsub:
    build:
      context: ./crates/pubsub
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - dii

  redis:
    image: "redis:alpine"
    networks:
      - dii
    ports:
      - "6380:6379"

networks:
  dii:

    